# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QuickOrder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  # Pods for QuickOrder

  # Your file path will be different, feel free to temporarily comment mine out

  project '/Users/edwardhuang/Documents/GitHub/mhackers-ios-intro/QuickOrder.xcodeproj'

end
